version: "3.8"

services:
  db:
    image: mysql:8.0.23
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root2mysql
      MYSQL_DATABASE: unicrawl
      MYSQL_USER: unicrawl
      MYSQL_PASSWORD: scrapy2mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:4.8.0
    restart: on-failure
    ports:
      - 8080:8080

  unicrawl:
    build: .
    container_name: unicrawl
    restart: on-failure
    ports:
      - "6800:6800"
    depends_on:
      - "db"

volumes:
  db_data:
